// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVkBj4YGjiKREB4_RjTyUhEnUFqGU77zs',
    appId: '1:723775785158:web:95626b3a5a7fe392476fc7',
    messagingSenderId: '723775785158',
    projectId: 'igarchu-53425',
    authDomain: 'igarchu-53425.firebaseapp.com',
    storageBucket: 'igarchu-53425.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMkeNkvR251CW-d2uSHL_O7XyYcjQh7zc',
    appId: '1:723775785158:android:3cd6bb41e3724264476fc7',
    messagingSenderId: '723775785158',
    projectId: 'igarchu-53425',
    storageBucket: 'igarchu-53425.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhut5_x8ZDZ4SOjM6wI6_NFsr2ZICggxc',
    appId: '1:723775785158:ios:a1724a2b388695e6476fc7',
    messagingSenderId: '723775785158',
    projectId: 'igarchu-53425',
    storageBucket: 'igarchu-53425.appspot.com',
    iosClientId: '723775785158-f975o0lbi228eeed8am11a4dvkqkscrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.igarchuCapstone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhut5_x8ZDZ4SOjM6wI6_NFsr2ZICggxc',
    appId: '1:723775785158:ios:a1724a2b388695e6476fc7',
    messagingSenderId: '723775785158',
    projectId: 'igarchu-53425',
    storageBucket: 'igarchu-53425.appspot.com',
    iosClientId: '723775785158-f975o0lbi228eeed8am11a4dvkqkscrq.apps.googleusercontent.com',
    iosBundleId: 'com.example.igarchuCapstone',
  );
}
